language: perl6
sudo: false
os:
  - linux
  - osx
perl6:
  - latest
  - '2020.10'
  - '2020.05.1'
install:
  - rakudobrew build zef
  - zef --depsonly install .
script:
  - prove -ve "raku -I."
  - zef install .
