os: Visual Studio 2015

platform: x64

install:
  # Install rakudostar for faster CI builds.
  - choco install rakudostar
  # Change to build folder
  - cd %APPVEYOR_BUILD_FOLDER%
  # Refresh environment variables so zef works
  - refreshenv

build: off

test_script:
  - zef --deps-only install .
  - prove -ve "perl6 -I."
  - zef install .

shallow_clone: true
